services:
  nsfw:
    build: .
    image: nsfw-go:latest
    container_name: nsfw-go
    restart: unless-stopped
    volumes:
      - /volume1/homes/schmidtfx/Photos:/photos:rw
      - /volume1/docker/synotagger/nsfw-output:/output:rw
      - /volume1/docker/synotagger/models:/models:ro
    command: [
      "-model","/models/320n.onnx",
      "-model-type","detector",
      "-input-name","images",
      "-output-name","output0",
      "-nchw","false",
      "-size","320",
      "-mean","0.485,0.456,0.406",
      "-std","0.229,0.224,0.225",
      "-classes","BELLY_EXPOSED,BUTTOCKS_EXPOSED,BREAST_EXPOSED,GENITALIA_F_EXPOSED,GENITALIA_M_EXPOSED",
      "-det-conf","0.25",
      "-det-iou","0.45",
      "-det-max","300",
      "-th","0.50",
      "-dir","/photos",
      "-out","/output/results.jsonl",
      "-csv","/output/results.csv",
      "-workers","4",
      "-state","/output/state.db",
      "-skip-unchanged",
      "-rehash-days","30",
      "-write-tags","-tag-prefix","nsfw","-tag-subs","auto","-sidecar"
    ]
